### ISSUE TITLE
BUG : NPE while updating user traits.

### ISSUE THREAD

**Issue by silicon-pranit** [rudderlabs/rudder-sdk-android#215] opened 2023-03-30 08:37 UTC
**Describe the bug**
Please provide the following information:

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.rudderstack.android.sdk.core.RudderContext.updateTraits(com.rudderstack.android.sdk.core.RudderTraits)' on a null object reference
>        at com.rudderstack.android.sdk.core.RudderElementCache.updateTraits(RudderElementCache.java:47)
>        at com.rudderstack.android.sdk.core.RudderMessage.updateTraits(RudderMessage.java:118)
>        at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:408)
>        at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:469)

**To Reproduce**
Not able to reproduce but have **980+** crashes reported in last **90** days

**Version of the _Android_ SDK**
Android SDK: **v1.10.0**

**Comment by itsdebs** [comment] 2023-03-30 09:23
@silicon-pranit Please provide your initialization snippet and let us know if this issue is happening on a particular device or android version.

**Comment by silicon-pranit** [comment] 2023-03-30 11:13
@itsdebs here is the initialisation snippet

```
val rudderClient = RudderClient.getInstance(
            context!!,
            BuildConfig.RudderStackWriteKey,
            RudderConfig.Builder()
                .withDataPlaneUrl(BuildConfig.DataPlaneUrl)
                .withTrackLifecycleEvents(true)
                .withRecordScreenViews(true)
                .build()
        )
RudderClient.setSingletonInstance(rudderClient)
```


Once this in done we call
```
RudderClient.getInstance()?.identify(userId, traits, options)
```

Observed on following OEMs:
- OnePlus [57%]
- Vivo [26%]
- Samsung [10%]
- Oppo [6%]
- Xiaomi [1%]

Observed on following Android Versions:
- 13 [10%]
- 12 [87%]
- 11 [1%]
- 9 [1%]
- 8 [1%]

**Comment by itsdebs** [comment] 2023-03-30 11:48
@silicon-pranit Are you running the snippet on Application class or elsewhere?

**Comment by itsdebs** [comment] 2023-04-10 07:13
@silicon-pranit Couldn't reproduce the error. May be this is due to some instrumentation error on app side. On a side note,
`RudderClient.setSingletonInstance(rudderClient)` is redundant in this use case. 
Closing this for now, please reopen in case some more information can be provided on this.

**Closed by itsdebs** 2023-04-10 07:13 UTC
Labels: bug
